version: 2
jobs:
  build:
    docker:
      - image: jakzal/phpqa:alpine
    steps:
      - checkout
      - run:
          name: Linting PHP files
          command: parallel-lint --exclude vendor .
      - run:
          name: Check code style
          command: php-cs-fixer fix -v --diff --dry-run --using-cache=no
workflows:
  version: 2
  build:
    jobs:
      - build
